[EPO-3920] Add content field to Hero
lsst-epo/ed-hub pull request #27
Opened 2020-10-16 19:57 UTC by georgegomez144

Add content with wysiwyg
Update header to plain text entry
Style accordingly

2020-10-16 20:54 UTC, blnkt requested changes
A little nuance here in terms of the twig stuff.  Additionally I'd like to request that you add a white "card" kind of div for this hero title and hero content to live inside so it will work against the background images regardless of what the images are.  This "card" can be a plain ol' div or give it a lil box shadow if you please.

2020-10-16 20:54 UTC, blnkt commented on templates/teachers/guide.twig
> - {% set headerText = entry.hero.one().header ?? entry.title %}
I'm pretty sure you want this as it was:
`{% set headerText = entry.hero.one().header ?? entry.title %}`
in order to handle the fallbacks.  As you have it, if one adds a hero image, but leaves the header field blank on the hero then it renders the hero entry id instead of the teachers guide entry title (which I think is the desired fallback).

This has trickle down effects for where the hero is instantiated in this file.  So the way this:
`{% include '_partials/hero' ignore missing with {'heroImg': hero, 'headerText': headerText,'isShort': true}  %}`
works is kind of like how props on a react component work.  So you'll need to update that too, and how those are used in the hero partial.  Let me know if you ever run into any questions about twig stuff.  Although it's been a while now, I've worked with twig extensively in the past and hopefully still remember some stuff.

2020-10-16 20:54 UTC, blnkt commented on templates/_partials/hero.twig
> +{% set heroContent =  headerText.heroContent ?? '' %}
see related comment below

2020-10-20 00:21 UTC, blnkt requested changes
A couple more suggestions, and some behavior from last round of feedback I'm still not seeing..

Also please rebase locally and address merge conflicts.

Otherwise love the looks of this hero heading card.

2020-10-20 00:21 UTC, blnkt commented on templates/_partials/hero.twig
> +    <div class="grid-x align-center c-hero__content">{{ headerContent ?? '' }}</div>
I recommend putting the margin-bottom that's on this h1 on the top of `c-hero__content` el instead, and then conditionally render both these els based on presence of headerText and headerContent respectively.  As is, if the content block is absent the heading is not vertically centered.  I'd do it like:
```
 .c-hero__header {
     ...
     + .c-hero__content {
          ...
          margin-top: stuff;
     }
}
```

2020-10-20 00:21 UTC, blnkt commented on templates/_partials/hero.twig
> +  <div class="grid-container c-card">
- Only render this card if `headerText` or `headerContent` exist.  Otherwise you'll get a lil empty card on some pages.
- Add some kind of margins or padding (all sides) to stop this card from running to the edges of the hero image container
![Screen Shot 2020-10-19 at 5 12 44 PM](https://user-images.githubusercontent.com/8166060/96524930-665b7f00-122e-11eb-8091-52a28e0302c6.png)
![Screen Shot 2020-10-19 at 5 13 01 PM](https://user-images.githubusercontent.com/8166060/96524949-71aeaa80-122e-11eb-9594-de53aa77d18d.png)

2020-10-20 00:21 UTC, blnkt commented on templates/teachers/guide.twig
> + {% set headerText = entry.hero.one().header.one() ?? entry.title %}
Still not seeing the `header` text, only ever see `entry.title`.  Would prefer `header` take precedence and `title` act as a fallback.  I thought `{% set headerText = entry.hero.one().header ?? entry.title %}` would probs do the trick, but did you find that was not effective?

2020-10-20 19:35 UTC, blnkt requested changes
Closer and closer.  I've called out a couple things still worth doing while you're refining this hero el.  A larger problem I'm seeing is a bunch of styles...I think exclusively related to unordered list?...are broken as of your last commit/force push.  Most is these trailing commas in each li's after, but also seems to have broken some of the typographic styles on nav items. 
Is probably all the same thing?  Is just something global that is used in a lot of places?  It's hard for me to guess as git registers all of your whitespace changes in components.scss so I can't really tell what really changed.  I've screen capped several instances I've spotted but once you identify the issue please do a more exhaustive check to ensure we've addressed the issue.
<img width="1157" alt="Screen Shot 2020-10-20 at 11 54 17 AM" src="https://user-images.githubusercontent.com/8166060/96635350-98bdb880-12d0-11eb-9ab1-7789025fff57.png">
<img width="1130" alt="Screen Shot 2020-10-20 at 11 53 27 AM" src="https://user-images.githubusercontent.com/8166060/96635363-9eb39980-12d0-11eb-98cd-f16b9a2ebc48.png"> 
<img width="1117" alt="Screen Shot 2020-10-20 at 11 53 56 AM" src="https://user-images.githubusercontent.com/8166060/96635378-a3784d80-12d0-11eb-87be-95cc4d94e535.png">
<img width="1117" alt="Screen Shot 2020-10-20 at 11 53 42 AM" src="https://user-images.githubusercontent.com/8166060/96635393-a83d0180-12d0-11eb-8ad5-6c06b2d889fd.png">

2020-10-20 19:35 UTC, blnkt commented on templates/teachers/guide.twig
> +{% include '_partials/hero' ignore missing with {'heroImg': hero, 'headerText': headerText, 'headerContent': headerContent, 'isShort': true}  %}
You need to pull this kind of change over to any templates that uses the hero partial and is exposed in the dashboard to content editors.  This is probably only those pages in the singles dashboard directory (we don't need to update the investigations land page templates since we aren't going to use those anymore).   As is those templates that use this hero partial have both headerText and headerContent as available fields in the dashboard, but currently only headerText renders on the frontend.

2020-10-20 19:35 UTC, blnkt commented on templates/_partials/hero.twig
> +  <div class="grid-container c-hero-card">
I'm still not seeing any styling to stop this card from running into the sides of the hero container.  
From last review comment:

> Add some kind of margins or padding (all sides) to stop this card from running to the edges of the hero image container

Please update.

2020-10-20 20:15 UTC, georgegomez144 commented
> Closer and closer. I've called out a couple things still worth doing while you're refining this hero el. A larger problem I'm seeing is a bunch of styles...I think exclusively related to unordered list?...are broken as of your last commit/force push. Most is these trailing commas in each li's after, but also seems to have broken some of the typographic styles on nav items.
> Is probably all the same thing? Is just something global that is used in a lot of places? It's hard for me to guess as git registers all of your whitespace changes in components.scss so I can't really tell what really changed. I've screen capped several instances I've spotted but once you identify the issue please do a more exhaustive check to ensure we've addressed the issue.
> <img alt="Screen Shot 2020-10-20 at 11 54 17 AM" width="1157" src="https://user-images.githubusercontent.com/8166060/96635350-98bdb880-12d0-11eb-9ab1-7789025fff57.png">
> <img alt="Screen Shot 2020-10-20 at 11 53 27 AM" width="1130" src="https://user-images.githubusercontent.com/8166060/96635363-9eb39980-12d0-11eb-98cd-f16b9a2ebc48.png">
> <img alt="Screen Shot 2020-10-20 at 11 53 56 AM" width="1117" src="https://user-images.githubusercontent.com/8166060/96635378-a3784d80-12d0-11eb-87be-95cc4d94e535.png">
> <img alt="Screen Shot 2020-10-20 at 11 53 42 AM" width="1117" src="https://user-images.githubusercontent.com/8166060/96635393-a83d0180-12d0-11eb-8ad5-6c06b2d889fd.png">

============

Seems while fixing the merge conflict, I broke this.

2020-10-20 20:48 UTC, georgegomez144 commented on templates/teachers/guide.twig
> +{% include '_partials/hero' ignore missing with {'heroImg': hero, 'headerText': headerText, 'headerContent': headerContent, 'isShort': true}  %}
There were a few pages (Index, Teachers & Glossary) where i tried to include the `entry.hero.one().headerContent` where it threw an error saying it could not get that prop, so on those pages, I have not included the header content.

2020-10-20 21:48 UTC, blnkt commented on templates/teachers/guide.twig
> +{% include '_partials/hero' ignore missing with {'heroImg': hero, 'headerText': headerText, 'headerContent': headerContent, 'isShort': true}  %}
Based on what you've written above I think you're just requesting the wrong field in your twig template.  Above, and elsewhere, like in `investigations/index.twig`, you've written `blahBlah.headerContent` but the handle for that field is `heroContent`.  I substituted `heroContent` in the templates you mentioned threw errors and that worked no prob.  I'll push this change up momentarily.

2020-10-20 21:53 UTC, blnkt commented on templates/teachers/guide.twig
> +{% include '_partials/hero' ignore missing with {'heroImg': hero, 'headerText': headerText, 'headerContent': headerContent, 'isShort': true}  %}
As for the investigation landing page.  That entry is not using the Hero in the dashboard it's still set up to only use an image.  Which was causing errors with the changes you made to that page.  But also, as I suggested above, we're not planning on using those pages for anything, so we can leave 'em be.  I've reverting your changes so they won't break on the frontend if we do end up wanting to re-purpose down the line.

2020-10-21 14:46 UTC, georgegomez144 commented on templates/teachers/guide.twig
> +{% include '_partials/hero' ignore missing with {'heroImg': hero, 'headerText': headerText, 'headerContent': headerContent, 'isShort': true}  %}
Sheesh, I created the entry and completely spaced what I named it...(that's embarrassing)...

2020-10-22 16:47 UTC, blnkt approved these changes

2020-10-22 16:47 UTC, merged