[EPO-3931] Create TOC for teacher's guide page
lsst-epo/ed-hub pull request #31
Opened 2020-10-21 15:16 UTC by georgegomez144

Update content structure and attrs

[F] Add structure to support sticky-sidenav

2020-10-23 22:51 UTC, blnkt requested changes
<img width="1087" alt="Screen Shot 2020-10-23 at 12 40 29 PM" src="https://user-images.githubusercontent.com/8166060/97046926-fe0de580-152c-11eb-8718-e3af6135710a.png">
- Sidebar should stop being sticky before it interrupts the footer (see screenshot above).  [See this foundation documentation](https://get.foundation/sites/docs/sticky.html#advanced) about how to accomplish using a "bottom" data attribute.

My instinct is to put the sidebar on the lefthand side.  But I would defer to Jose's opinion if you would share a screenshot with him and get his input.

2020-10-23 22:51 UTC, blnkt commented on templates/teachers/guide.twig
> +                                <div id="introduction" data-magellan-target="introduction">
double `id`s and `data-magellan-target`s?

2020-10-23 22:51 UTC, blnkt commented on templates/teachers/guide.twig
> +                                    </ul>
- Quick links should update location history just as tabs do, so a user can easily return to the same portion of the page, and so their browser back/forward buttons do what they would expect.
- Active classes like we get with tabs too?

2020-10-23 22:51 UTC, blnkt commented on templates/teachers/guide.twig
> +                            </ul>
- Quick links should update location history just as tabs do, so a user can easily return to the same portion of the page, and so their browser back/forward buttons do what they would expect.
- Active classes like we get with tabs too?

2020-10-26 17:52 UTC, georgegomez144 commented on src/scss/components.scss
> +
There is an attribute `data-offset`, but it doesn't work for me. I've followed their tutorial videos that show how this attribute works, but for some reason it isn't working in this instance. I believed I used this attr for the glossary magellan and that one worked perfectly. My guess is that there are too many "sticky" instances on this page. Either way, the spacer (with the added negative margin) seems to be the correct solution here.

2020-10-28 21:01 UTC, blnkt approved these changes

2020-10-28 21:33 UTC, merged