[EPO-4085] Create individual assets for prepost and summative files
lsst-epo/ed-hub pull request #63
Opened 2020-12-11 16:35 UTC by georgegomez144

[C] Remove deprecated composer command

[F] Add two assets for assessments

These two new assets are for Pre/Post Test and Summative Assessment download files.

[C] Create individual assets for prepost and summative files

2020-12-14 21:48 UTC, blnkt requested changes
Couple quick changes called out inline.

We wanna give each of these downloads a headings like they had when they were included as content on the page.  That way the User can still use the sidebar to navigate between the various sections in "Assessments."  So please add that.  You should use the existing UI Elements globals for those headings.  Also, Let's go ahead and anticipate Ardis wanting to include a couple lines of text to contextualize the downloads for" Pre/Post" and "Summative".  So the structure for each section will be like:

HEADING
EXPLANATORY TEXT
DOWNLOADS

and an example might look like:

### Summative Assessment

In the Summative Assessment you'll find everything you need for a great learning experience with you students.  Pay special attention to the colored coded something or other as it relates to the science rubric.  We have provided this Assessment in multiple file formats for your convenience.

"I'm a pdf version download button"

...roughly...

2020-12-14 21:48 UTC, blnkt commented on templates/_partials/guide/downloadable_materials.twig
> +      </li>
I forgot that we'll wanna have multiple downloads for each assessment later on (like a pdf version & a word version), so please keep these as loops instead of using `.one()`

2020-12-14 21:48 UTC, blnkt commented on templates/_partials/guide/assessments.twig
> +                {% if (entry.preTestPostTestFile|length or entry.summativeAssessmentFile|length) and isTeacher %}
you're already nested in a partial that is conditionally visible to teachers, so I think is superfluous check of `isTeacher` here.  Right?

2020-12-14 21:48 UTC, blnkt commented on templates/_partials/guide/assessments.twig
> +          {% if (entry.preTestPostTestFile|length or entry.summativeAssessmentFile|length) and isTeacher %}
you're already nested in a partial that is conditionally visible to teachers, so I think is superfluous check of `isTeacher` here.  Right?

2020-12-14 21:48 UTC, blnkt commented on templates/_partials/guide/downloadable_materials.twig
> +          download="{{ entry.preTestPostTestFile.one().filename }}" class="hollow button">
Please style these like we have the other buttons on this site: solid blue like the "Start Investigation"

2020-12-14 21:48 UTC, blnkt commented on templates/_partials/guide/assessments.twig
> +          {# LEAVE IN THIS SECTION TILL ALL CONTENT IS TRANSFERED TO THE NEW STRUCTURE #}
I think it's gonna be confusing for folks to see this content in here that we're not intending on using, so I would suggest we comment out for now.  In terms of "transferring" it, it's the backend stuff that we don't wanna lose track of, because we'll copy and paste it over, not the stuff on the frontend.  And even then, it's only the formative assessment that we'll need to reconstitute, the summative and pre/post test content is gonna be in the downloads.  If we really need to refer to how they look on the frontend to complete the work of creating the downloables, then we can uncomment at that point and reference on the frontend.  At this time we want folks, especially Ardis, to see what a 'ready for pilot testing " Ed Site looks like.  If you're feeling different, or anticipating something I'm not thinking of do tell.

2020-12-15 17:37 UTC, georgegomez144 commented on templates/_partials/guide/downloadable_materials.twig
> +      </li>
added for loop 👍

2020-12-15 17:38 UTC, georgegomez144 commented on templates/_partials/guide/assessments.twig
> +                {% if (entry.preTestPostTestFile|length or entry.summativeAssessmentFile|length) and isTeacher %}
Nice catch. Updated.

2020-12-15 17:39 UTC, georgegomez144 commented on templates/_partials/guide/assessments.twig
> +          {# LEAVE IN THIS SECTION TILL ALL CONTENT IS TRANSFERED TO THE NEW STRUCTURE #}
wow, my mind over thought this.

2020-12-15 19:30 UTC, blnkt requested changes
Please use the existing UI Elements globals for those headings, not new custom heading fields.  This way the navigation and informational hierarchy across teacher's guides will always be consistent regardless of which investigation a teacher is reading about.

2020-12-15 21:59 UTC, blnkt approved these changes

2020-12-15 21:59 UTC, merged